--RegisterNetEvent('FuriousFoxGG:giveWeapons')
--AddEventHandler('FuriousFoxGG:giveWeapons', function()
--	giveWeapon("weapon_nightstick")
--    giveWeapon("weapon_stungun")
--    giveWeapon("weapon_flashlight")
--    giveWeapon("weapon_combatpistol")
--    GiveWeaponComponentToPed(GetPlayerPed(-1), 1593441988, 0x359B7AAE)
--    giveWeapon("weapon_carbinerifle")
--    GiveWeaponComponentToPed(GetPlayerPed(-1), -2084633992, 0x7BC4CDDC)                      -------------------------------------------------
--    GiveWeaponComponentToPed(GetPlayerPed(-1), -2084633992, 0xC164F53)                       ------------------Soon to come-------------------
--    GiveWeaponComponentToPed(GetPlayerPed(-1), -2084633992, 0xA0D89C42)                      -------------------------------------------------
--    giveWeapon("weapon_pumpshotgun")
--    GiveWeaponComponentToPed(GetPlayerPed(-1), 487013001, 0x7BC4CDDC)
--    SetPedArmour(GetPlayerPed(-1), 100)
--end)
--RegisterNetEvent('FuriousFoxGG:removeWeapons')
--AddEventHandler('FuriousFoxGG:removeWeapons', function()
	-- Remove weapons and armor
--	SetPedArmour(GetPlayerPed(-1), 0)
--	RemoveAllPedWeapons(GetPlayerPed(-1), true);
--end)